local Color = require("public.color")

describe("Color.fromRgba", function()
  test("red", function()
    local col = Color.fromRgba(255, 0, 0)
    expect(col).toDeepEqual(Color.colors.red)
  end)
  test("blue", function()
    local col = Color.fromRgba(0, 0, 255)
    expect(col).toDeepEqual(Color.colors.blue)
  end)
  test("maroon", function()
    local col = Color.fromRgba(128, 0, 0)
    expect(col).toDeepEqual(Color.colors.maroon)
  end)
  test("gray", function()
    local col = Color.fromRgba(128, 128, 128, 255)
    expect(col).toDeepEqual(Color.colors.gray)
  end)
  test("not lime", function()
    local col = Color.fromRgba(0, 255, 0, 0.99)
    expect(col).toNotDeepEqual(Color.colors.lime)
  end)
  test("not purple", function()
    local col = Color.fromRgba(128, 0, 128, 0)
    expect(col).toNotDeepEqual(Color.colors.purple)
  end)
end)

describe("Color.toRgba", function()
  test("red", function()
    local col = Color.toRgba(Color.colors.red)
    expect(col).toDeepEqual({255, 0, 0, 255})
  end)
  test("blue", function()
    local col = Color.toRgba(Color.colors.blue)
    expect(col).toDeepEqual({0, 0, 255, 255})
  end)
  test("maroon", function()
    local col = Color.toRgba(Color.colors.maroon)
    expect(col).toDeepEqual({128, 0, 0, 255})
  end)
  test("gray", function()
    local col = Color.toRgba(Color.colors.gray)
    expect(col).toDeepEqual({128, 128, 128, 255})
  end)
  test("not lime", function()
    local col = Color.toRgba(Color.colors.lime)
    expect(col).toNotDeepEqual({0, 255, 0, 200})
  end)
  test("not purple", function()
    local col = Color.toRgba(Color.colors.purple)
    expect(col).toNotDeepEqual({128, 0, 128, 0})
  end)
end)

describe("Color.fromHex", function()
  test("basic hex string", function()
    local col = Color.fromHex("00FF55")
    expect(col).toAlmostDeepEqual({0, 1, 0.33333, 1})
  end)
  test("0x string", function()
    local col = Color.fromHex("0xCC8823")
    expect(col).toAlmostDeepEqual({0.8, 0.5333, 0.1373, 1})
  end)
  test("0x string with alpha", function()
    local col = Color.fromHex("0x38F2D8A3")
    expect(col).toAlmostDeepEqual({0.220, 0.949, 0.847, 0.639})
  end)
  test("# string", function()
    local col = Color.fromHex("#44DF32")
    expect(col).toAlmostDeepEqual({0.267, 0.875, 0.196, 1})
  end)
  test("# string with alpha", function()
    local col = Color.fromHex("#C3B87E77")
    expect(col).toAlmostDeepEqual({0.765, 0.722, 0.494, 0.467})
  end)
  test("black", function()
    local col = Color.fromHex("000000")
    expect(col).toDeepEqual({0, 0, 0, 1})
  end)
end)

describe("Color.toHex", function()
  test("RGB", function()
    local col = Color.toHex(0, 1, 0.33333)
    expect(col).toEqual("00FF55")
  end)
  test("RGBA", function()
    local col = Color.toHex(0.8, 0.5333, 0.1373, 1)
    expect(col).toEqual("CC8823FF")
  end)
  test("White", function()
    local col = Color.toHex(1, 1, 1, 1)
    expect(col).toEqual("FFFFFFFF")
  end)
  test("Black", function()
    local col = Color.toHex(0, 0, 0)
    expect(col).toEqual("000000")
  end)
end)

describe("Color.fromHsv", function()
  test("", function()
    local col = Color.fromHsv(123, 0.45, 0.671)
    expect(col).toAlmostDeepEqual({0.369, 0.671, 0.384, 1})
  end)
  test("h > 360", function()
    local col = Color.fromHsv(845, 0.5, 1, 0.333)
    expect(col).toAlmostDeepEqual({0.50196, 1, 0.542, 0.333}, 2)
  end)
  test("h < 0", function()
    local col = Color.fromHsv(-235, 0.5, 1, 0.333)
    expect(col).toAlmostDeepEqual({0.50196, 1, 0.542, 0.333}, 2)
  end)
end)

describe("Color.toHsv", function()
  test("", function()
    local col = Color.toHsv(0.1176, 0.10196, 0.10588)
    expect(col).toAlmostDeepEqual({344.962, 0.1333, 0.1176, 1})
  end)
  test("", function()
    local col = Color.toHsv(0.6196, 0.9294, 0.2118)
    expect(col).toAlmostDeepEqual({85.903, 0.7722, 0.9294, 1})
  end)
  test("", function()
    local col = Color.toHsv(0.247, 0.741, 0.804, 0.5)
    expect(col).toAlmostDeepEqual({186.786, 0.6927, 0.8039, 0.5})
  end)
  test("black", function()
    local col = Color.toHsv(0, 0, 0, 1)
    expect(col).toDeepEqual({0, 0, 0, 1})
  end)
  test("white", function()
    local col = Color.toHsv(1, 1, 1, 0.3)
    expect(col).toDeepEqual({0, 0, 1, 0.3})
  end)
end)

describe("Color.set", function()
  test("red", function()
    local col = Color.set("red")
    expect(col).toDeepEqual({1, 0, 0, 1})
  end)
  test("cyan", function()
    local col = Color.set("cyan")
    expect(col).toDeepEqual({0, 1, 1, 1})
  end)
  test("olive (table)", function()
    local col = Color.set(Color.fromRgba({127.7, 127.7, 0, 255}))
    expect(col).toAlmostDeepEqual({0.5, 0.5, 0, 1})
  end)
end)
